# Generated by Django 4.0.4 on 2022-05-18 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crms_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authuser',
            name='user_type',
            field=models.PositiveSmallIntegerField(choices=[(2, 'Customer'), (1, 'Product Manager')], null=True),
        ),
    ]
