# Generated by Django 4.0.4 on 2022-05-25 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crms_app', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authuser',
            name='user_type',
            field=models.PositiveSmallIntegerField(choices=[(4, 'Reviewer'), (3, 'Customer Manager'), (1, 'Product Manager'), (2, 'Customer')], null=True),
        ),
    ]
