# Generated by Django 4.0.4 on 2022-05-25 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crms_app', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authuser',
            name='user_type',
            field=models.PositiveSmallIntegerField(choices=[(3, 'Customer Manager'), (4, 'Reviewer'), (2, 'Customer'), (1, 'Product Manager')], null=True),
        ),
    ]
