# Generated by Django 4.0.4 on 2022-05-18 07:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pcims_app', '0001_initial'),
        ('crms_app', '0003_alter_authuser_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerinformation',
            name='productCatalog',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pcims_app.productcatalog'),
        ),
        migrations.AlterField(
            model_name='authuser',
            name='user_type',
            field=models.PositiveSmallIntegerField(choices=[(2, 'Customer'), (1, 'Product Manager'), (3, 'Customer Manager')], null=True),
        ),
    ]
