# Generated by Django 4.0.4 on 2022-05-24 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crms_app', '0004_customerinformation_productcatalog_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authuser',
            name='user_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Product Manager'), (2, 'Customer'), (3, 'Customer Manager'), (4, 'Reviewer')], null=True),
        ),
    ]
