# Generated by Django 4.0.4 on 2022-05-29 11:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crms_app', '0009_alter_authuser_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authuser',
            name='user_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Product Manager'), (4, 'Reviewer'), (2, 'Customer'), (3, 'Customer Manager')], null=True),
        ),
        migrations.AlterField(
            model_name='customerreview',
            name='rating',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)]),
        ),
    ]
