# Generated by Django 4.0.4 on 2022-05-29 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crms_app', '0010_alter_authuser_user_type_alter_customerreview_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authuser',
            name='user_type',
            field=models.PositiveSmallIntegerField(choices=[(2, 'Customer'), (3, 'Customer Manager'), (4, 'Reviewer'), (1, 'Product Manager')], null=True),
        ),
        migrations.AlterField(
            model_name='customerreview',
            name='productReview',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
