# Generated by Django 4.0.4 on 2022-05-24 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crms_app', '0012_alter_authuser_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authuser',
            name='user_type',
            field=models.PositiveSmallIntegerField(choices=[(3, 'Customer Manager'), (2, 'Customer'), (1, 'Product Manager')], null=True),
        ),
    ]
