# Generated by Django 4.0.4 on 2022-05-29 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crms_app', '0011_alter_authuser_user_type'),
        ('crms_app', '0013_alter_authuser_user_type_and_more'),
    ]

    operations = [
    ]
