# Generated by Django 4.0.4 on 2022-05-30 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crms_app', '0023_alter_authuser_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerreview',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='authuser',
            name='user_type',
            field=models.PositiveSmallIntegerField(choices=[(3, 'Customer Manager'), (4, 'Reviewer'), (2, 'Customer'), (1, 'Product Manager')], null=True),
        ),
    ]
