# Generated by Django 4.0.4 on 2022-05-30 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crms_app', '0024_alter_authuser_user_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authuser',
            name='user_type',
            field=models.PositiveSmallIntegerField(choices=[(2, 'Customer'), (3, 'Customer Manager'), (4, 'Reviewer'), (1, 'Product Manager')], null=True),
        ),
    ]
