# Generated by Django 4.0.4 on 2022-05-30 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crms_app', '0024_customerreview_picture_alter_authuser_user_type'),
        ('crms_app', '0025_alter_authuser_user_type'),
    ]

    operations = [
    ]
