# Generated by Django 4.0.4 on 2022-05-25 04:57

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('rating', models.FloatField(default=0)),
                ('description', models.TextField(blank=True, null=True)),
                ('stocks', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('reorderlvl', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('sellingprice', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('discount', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('isarchived', models.BooleanField(default=False)),
                ('isFeatured', models.BooleanField(default=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pcims_app.category')),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=b'I01\n')),
                ('address', models.CharField(max_length=200, null=b'I01\n')),
                ('email', models.CharField(max_length=200, null=b'I01\n')),
                ('telephone', models.CharField(max_length=200, null=b'I01\n')),
                ('contactperson', models.CharField(max_length=200, null=b'I01\n')),
                ('isarchived', models.BooleanField(default=False)),
                ('displaypicture', models.ImageField(blank=True, default='/default_pfp.png', null=True, upload_to='suppliers')),
            ],
        ),
        migrations.CreateModel(
            name='SupplierProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leadtime', models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('supplierprice', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('discount', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('isarchived', models.BooleanField(default=False)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pcims_app.product')),
                ('supplier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pcims_app.supplier')),
            ],
        ),
        migrations.CreateModel(
            name='Reviewer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('address', models.CharField(max_length=200, null=True)),
                ('profilepicture', models.ImageField(blank=True, default='/default_pfp.png', null=True, upload_to='')),
                ('contact', models.CharField(max_length=200, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('details', models.TextField(blank=True, null=True)),
                ('rating', models.FloatField(null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pcims_app.product')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pcims_app.reviewer')),
            ],
        ),
        migrations.CreateModel(
            name='ProductPhotos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(null=True, upload_to='images')),
                ('filename', models.TextField(max_length=1000, null=True)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='pcims_app.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profilepicture', models.ImageField(blank=True, default='default_pfp.png', null=True, upload_to='')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProductCatalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('details', models.TextField(blank=True)),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
                ('products', models.ManyToManyField(to='pcims_app.product')),
            ],
        ),
    ]
