# Generated by Django 4.0.4 on 2022-05-25 05:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pcims_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productphotos',
            name='product',
            field=models.ForeignKey(default='/default_product.png', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='pcims_app.product'),
        ),
    ]
