# Generated by Django 4.0.4 on 2022-05-25 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcims_app', '0002_alter_product_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcatalog',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='productphotos',
            name='filename',
            field=models.TextField(max_length=1000, null=True),
        ),
    ]
