# Generated by Django 4.0.4 on 2022-05-24 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0027_alter_authuser_user_type_alter_product_discount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authuser',
            name='user_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Product Manager'), (3, 'Customer Manager'), (2, 'Customer'), (4, 'Reviewer')], null=True),
        ),
    ]
