# Generated by Django 4.0.4 on 2022-05-24 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0029_alter_authuser_user_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvideos',
            name='product',
        ),
        migrations.AddField(
            model_name='catalog',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='catalog',
            name='products',
            field=models.ManyToManyField(to='catalog.product'),
        ),
        migrations.AlterField(
            model_name='authuser',
            name='user_type',
            field=models.PositiveSmallIntegerField(choices=[(3, 'Customer Manager'), (1, 'Product Manager'), (4, 'Reviewer'), (2, 'Customer')], null=True),
        ),
        migrations.AlterField(
            model_name='catalog',
            name='details',
            field=models.TextField(blank=True),
        ),
        migrations.DeleteModel(
            name='ProductCatalog',
        ),
        migrations.DeleteModel(
            name='ProductVideos',
        ),
    ]
